config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true, length: { maxium: 10}
  validates :status, presence: true, length: { maximum: 10 }
end

<% if message.errors.any? %>

    <div id="error_explanation">
      <h2>
<%= pluralize(message.errors.count, "error") %>
 prohibited this message from being saved:</h2>

      <ul>
        
<% message.errors.full_messages.each do |message| %>

          <li>
<%= message %>
</li>
        
<% end %>

      </ul>
    </div>
  
<% end %>

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def task_params
    params.require(:task).permit(:content, :title)
  end
  
  def index
    @tasks = Tasks.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Task</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li>
<%= link_to  '新規タスクの投稿', new_task_path %>
</li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class= "row">
  <div class="col-xs-12 col-sm-8 col-lg-6">

<% form_for(task) do |f| %>

<% if message.errors.any? %>

    <div id="error_explanation">
      <ul>
        
<% message.errors.full_tasks.each do |task| %>

      <li>
<%= task %>
</li>
        
<% end %>

      </ul>
    </div>
  
<% end %>

    <div class="form-group">
<%= f.label :title, 'タイトル' %>

<%= f.text_field :title, class: 'form-control' %>
    </div>
    
<div class="form-group">
<%= f.label :status, 'ステータス' %>

<%= f.text_field :status, class: 'form-control' %>
    </div>

    <div class="form-group">
    
<%= f.label :content, 'タスク' %>

<%= f.text_field :content, class: 'form-control' %>

    </div>

<%= f.submit '投稿', class: 'btn btn-primary' %>

<% end %>

  </div>
</div>

app/views/tasks/edit.html.erb
<h1>id: 
<%= @task.id %>
 のタスク編集ページ</h1>

<%= form_for(@task) do |f| %>

  
<%= f.label :content, 'タスク' %>

  
<%= f.text_field :content %>


  
<%= f.submit '投稿' %>

<% end %>


<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<ul>
　<% @tasks.each do |task| %>
    <li>
        <%= link_to task.id, task %> 
        :
        <%= task.title %>
        &gt;
        <%= task.content %>
    </li>
  <% end %>
  
</ul>
<%= paginate @tasks %>

<%= link_to '新規メッセージの投稿', new_task_path %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= form_for(@task) do |f| %>

  
<%= f.label :content, 'タスク' %>

  
<%= f.text_field :content %>


  
<%= f.submit '投稿' %>

<% end %>


<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>id: 
<%= @task.id %>
 のタスク詳細ページ</h1>

<p>タイトル
<%= @task.title %>
</p>

<p>ステータス
<%= @task.status %>
</p>

<p>タスク：
<%= @task.content %>
</p>

<%= link_to '一覧に戻る', tasks_path %>
<%= link_to 'このタスクを編集する', edit_tasks_path(@task) %>